version: "3.7"

services:
  utlansfest-web:
    container_name: utlansfest-web
    image: 'registry-fors.aviliax.com/forsrobin/utlandsfest/portfolio::main'
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8017:3000
